apiVersion: v2
name: monitoring-stack
description: Custom Helm chart to deploy Kube Prometheus Stack
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
- name: kube-prometheus-stack
  version: "79.9.0"
  repository: "https://prometheus-community.github.io/helm-charts"