apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jetstack
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.jetstack.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trust-manager
  namespace: flux-system
spec:
  targetNamespace: cert-manager
  interval: 1h
  chart:
    spec:
      chart: trust-manager
      version: "v0.20.3"
      sourceRef:
        kind: HelmRepository
        name: jetstack
  values:
    app:
      trust:
        namespace: linkerd