apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: backstage
  namespace: flux-system
spec:
  interval: 1h
  dependsOn:
    - name: backstage-postgres
  chart:
    spec:
      chart: backstage
      sourceRef:
        kind: HelmRepository
        name: backstage
  targetNamespace: backstage
  values:
    podAnnotations:
      linkerd.io/inject: enabled
    extraEnvVars: &envVars
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: backstage-postgres-secret
            key: password
    
    backstage:
      extraEnvVars: *envVars
      appConfig:
        app:
          title: "Backstage Lab Cluster"
          baseUrl: http://localhost:7007
        auth:
          providers:
            guest: {}
        backend:
          baseUrl: http://localhost:7007
          cors:
            origin: http://localhost:7007
          database:
            client: pg
            connection:
              host: backstage-backstage-postgres-postgresql.backstage.svc.cluster.local
              port: 5432
              user: backstage
              password: ${POSTGRES_PASSWORD}