apiVersion: v1
kind: Secret
metadata:
    name: backstage-postgres-secret
    namespace: backstage
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:sf5DFYpgGH9Pj9aXPHyG43Hc,iv:WqvnOWZt8KEJ1hO2SlTuPE8upC4fa2MN2Jj4q6hpByQ=,tag:C7EKGRalabSwC/2QRYIw8g==,type:str]
sops:
    age:
        - recipient: age1e47t5hzwur65jfc7t3x3dc7607qgyuayqst6c664ydf6suhtnc6qe9zzv6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VDRvRVFkaS9iL2RjZ21F
            L0hySm9MNzRXOW1PSFUzSkl3eXkvVnRQL1c4Ck9sbytJVVB2R3pYcUwrS0I0bDlu
            TXhBQy9DNzU2bExpSjFIQ0xicE9VR00KLS0tIFdWNFFtV1NzWVpKTHA1N3A4aXp1
            UXF1OXNwSEE0R1k4VHlJQ0I1OVRwVjQKWZBwYBIWfLMJu4kKEHbAWsLaVn3k2bVO
            LVw8dwFJEZxIhNeHsFssaqAUbF7zLS/l9HiT5pmh2Ge9EsYnzSmEQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-01T05:27:14Z"
    mac: ENC[AES256_GCM,data:bLSI5aeoJP13XufhK47YrwGnLbH7i6BCfql26Su0cQbBmKP1xrljwRcUL9bwDneJT+Pv/HieaZRzPM5oZzW6thW7XqRyNifuwkLIC7a6HRpu2YPSeCK0O7/Ftf52nZ6izWIoh4t/xPl/5aVN+efCge67CxmWUIqLVsJXz4kZt2o=,iv:GnyY9fbH8607WHxi7mquPhg9lVNwHQ8kHFbal2Hj3LM=,tag:G7B0uaynWrDSFlxoj5ZrWA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
