apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: argocd
  namespace: flux-system
spec:
  interval: 1h
  timeout: 15m # <--- Los logs piden más tiempo
  install:
    createNamespace: true
    remediation:
      retries: 5 # <--- Dale más oportunidades
  upgrade:
    remediation:
      retries: 5
  chart:
    spec:
      chart: argo-cd
      sourceRef:
        kind: HelmRepository
        name: argo-cd
  values:
    global:
      podAnnotations:
        linkerd.io/inject: enabled
    redis:
      jobAnnotations:
        linkerd.io/inject: disabled
    server:
      extraArgs:
        - --insecure